### ISSUE TITLE
An opinion 

### ISSUE THREAD

**Issue by andreujuanc** [jay-most/cosmosdb-react-native#1]
Hi,
I like the effort on this guide, but I have a serious concerns about this pattern.

First, you are hardcoding credentials in the source code. Those at least should be injected somehow on build/run time.

Second, and most important, you are using those credentials out in the wild, on the client. You should never, EVER, do that. Unless of course this app is only for you, or those credentials are data scoped somehow (which I believe you cannot do that, a-la-firebase).

You might know this principles, and you just wanted to show capabilities, but as when it happened years ago with PHP, this examples will be copy pasted and 💯 used in a production app somewhere even if it wasn't your intention. 

My suggestion is that we should always use best practices, especially security related ones, even if the guide/tutorial is small or just a snipped.

Best!

**Comment by jay-most** [comment]
This sample is no different than any other Microsoft sample. Thanks for your interest.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andreujuanc** [comment]
I'm sorry but I don't agree. there are plenty of good security practices all around Microsoft docs.  And even if there weren't , it's not an excuse to continue that bad trend.


This will mislead people. Please think about this.
